<?php

use Illuminate\Database\Seeder;

class ExampleUsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'role_id' => 1,
                'name' => '管理員',
                'email' => 'admin@goblinlab.org',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$cv3Hh6dyTGTt5ohLQMVCHOG4KqqCStXMX6Qed7K9je0zxxSKt8/x.',
                'remember_token' => 'Z4lbsw88fmuihEvYCxFOWftfCS4R9EIyoLZKPgX9X6bUlLFKQkuO9FBA0dqk',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'admin',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'role_id' => 2,
                'name' => '益貞雅',
                'email' => 'catalina.mraz@example.com',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => '0Ngtgu9KOb',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'pfahey',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'role_id' => 2,
                'name' => '羿柏柏',
                'email' => 'russel.gabriel@example.org',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => '82OpOLSPmB',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'bailey.olaf',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'role_id' => 2,
                'name' => '麻哲',
                'email' => 'gerson20@example.org',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'oNX6df7BsD',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'eichmann.damion',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'role_id' => 2,
                'name' => '白庭鈺',
                'email' => 'makenzie22@example.org',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'Indr71OqJx',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'rutherford.hazel',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'role_id' => 2,
                'name' => '祝萍琬',
                'email' => 'neil57@example.com',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => '1XYiEnEQY9',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'oruecker',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'role_id' => 2,
                'name' => '蓬萍如',
                'email' => 'vernon.volkman@example.com',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => '6WNrvrnOs9',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'hyatt.blanca',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'role_id' => 2,
                'name' => '雙貞婷',
                'email' => 'bradley11@example.com',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => '04wVx6KW8b',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'wilkinson.kenyon',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'role_id' => 2,
                'name' => '林心',
                'email' => 'hayes.chase@example.net',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'bdhrCwDYlq',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'rath.georgette',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'role_id' => 2,
                'name' => '東郭家',
                'email' => 'jana.barton@example.org',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'p3ez8nf4FA',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'okon.keon',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'role_id' => 2,
                'name' => '辛郁',
                'email' => 'roselyn.lesch@example.org',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'R2UTFJx2u4',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'mhilpert',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'role_id' => 2,
                'name' => '尚芬',
                'email' => 'rhegmann@example.org',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'clYCoR1ROM',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'nathaniel.herzog',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'role_id' => 2,
                'name' => '謝豪君',
                'email' => 'mking@example.org',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'bH1mE3qaPD',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'mann.vickie',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'role_id' => 2,
                'name' => '湯宗承',
                'email' => 'nheaney@example.net',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'Gei2w2tjpi',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'abernathy.issac',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'role_id' => 2,
                'name' => '房霖宏',
                'email' => 'senger.ladarius@example.net',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'wjo3vUer5N',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'itorphy',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'role_id' => 2,
                'name' => '邵美瑋',
                'email' => 'jacobson.gaetano@example.org',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'cWoKp83toi',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'wolf.lucius',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'role_id' => 2,
                'name' => '赫連蓉涵',
                'email' => 'glehner@example.com',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'cWYAAmX9na',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'alysha29',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'role_id' => 2,
                'name' => '聞人琪穎',
                'email' => 'waelchi.shakira@example.org',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'w6c04D3gvb',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'beier.assunta',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'role_id' => 2,
                'name' => '冀承宇',
                'email' => 'hsteuber@example.com',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => '56JrLhLCoO',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'jarod.hettinger',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'role_id' => 2,
                'name' => '微生郁馨',
                'email' => 'qthiel@example.org',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'M3lWgoKfv4',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'nwalker',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'role_id' => 2,
                'name' => '郤芬婉',
                'email' => 'connie60@example.org',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'Vz3lF4gFrn',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'ewest',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'role_id' => 2,
                'name' => '申屠軒瑋',
                'email' => 'hboyer@example.com',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'p4RSRRCTtM',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'mireya14',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'role_id' => 2,
                'name' => '薄萱雯',
                'email' => 'rolando57@example.net',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'wPWYdeSesE',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'gianni21',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'role_id' => 2,
                'name' => '商信',
                'email' => 'marcel94@example.net',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'DbpHBjBILN',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'ldietrich',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'role_id' => 2,
                'name' => '閔信柏',
                'email' => 'erdman.ozella@example.com',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => '731UJsNrXx',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'krystel.kuphal',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'role_id' => 2,
                'name' => '儲詩',
                'email' => 'hayes.gillian@example.org',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'zCDsGqpqvy',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'kaia.balistreri',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'role_id' => 2,
                'name' => '束華',
                'email' => 'jfritsch@example.net',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'gaEKPbPaSA',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'linnea.koss',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'role_id' => 2,
                'name' => '韋偉彥',
                'email' => 'jayde.torp@example.org',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'SFFcWZT42Q',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'veum.earl',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'role_id' => 2,
                'name' => '裘家',
                'email' => 'helen24@example.net',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'RlWh9l5hHf',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'johns.bethel',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'role_id' => 2,
                'name' => '倪玲',
                'email' => 'diana55@example.net',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'gvMnugFpVw',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'koepp.freeman',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'role_id' => 2,
                'name' => '雲芳嘉',
                'email' => 'rosella.hilpert@example.net',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'ImiMWFFn3G',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'wtrantow',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'role_id' => 2,
                'name' => '沈嘉宇',
                'email' => 'austen76@example.org',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => '0S1T5a8dmo',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'obuckridge',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'role_id' => 2,
                'name' => '羅依',
                'email' => 'jones.rudy@example.com',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'FrJekyzS2a',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'bartoletti.antonietta',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'role_id' => 2,
                'name' => '郜冠',
                'email' => 'egraham@example.org',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'RNMKlM1Heb',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'uokeefe',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'role_id' => 2,
                'name' => '簡霖賢',
                'email' => 'owelch@example.org',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'iDwK0yP4jF',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'von.maurine',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'role_id' => 2,
                'name' => '笪鈺筱',
                'email' => 'nienow.bill@example.org',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => '9UlrlUPTLz',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'buck.abshire',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'role_id' => 2,
                'name' => '黨冠美',
                'email' => 'qkohler@example.org',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'byHNoFufwL',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'kemmer.eladio',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'role_id' => 2,
                'name' => '聞人樺',
                'email' => 'waters.nola@example.com',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'L5mOqgQouJ',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'brigitte.willms',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'role_id' => 2,
                'name' => '鍾蓉貞',
                'email' => 'mohammed.bergnaum@example.org',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'UsqVeQUB8y',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'collins.vivien',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'role_id' => 2,
                'name' => '仲孫賢建',
                'email' => 'okozey@example.net',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => '7eEnSZMcY3',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'olaf.waters',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'role_id' => 2,
                'name' => '文嘉',
                'email' => 'malachi.erdman@example.com',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'StzUtYChox',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'derrick35',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'role_id' => 2,
                'name' => '懷筑思',
                'email' => 'dahlia26@example.net',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'SyLji5nkdb',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'herzog.jaren',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'role_id' => 2,
                'name' => '那傑',
                'email' => 'francis.greenholt@example.com',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'GQQ3gHP2b5',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'smith.alene',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'role_id' => 2,
                'name' => '陶思承',
                'email' => 'fwillms@example.net',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'qID0lP1pQA',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'litzy.ferry',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'role_id' => 2,
                'name' => '郤宗',
                'email' => 'deion59@example.com',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'cjYrUsRXNM',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'omclaughlin',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'role_id' => 2,
                'name' => '顏佳樺',
                'email' => 'oharris@example.org',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => '0kI1eIdTmt',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'shanahan.tanya',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'role_id' => 2,
                'name' => '雷建',
                'email' => 'hane.koby@example.com',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => '4W45ABcsBf',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'wolf.carissa',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'role_id' => 2,
                'name' => '岑婷君',
                'email' => 'fspencer@example.org',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'ahMamC0Rux',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'wlegros',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'role_id' => 2,
                'name' => '戎文雯',
                'email' => 'scottie.heaney@example.net',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'Ai2JseX8Kt',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'ethel.hackett',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'role_id' => 2,
                'name' => '查家偉',
                'email' => 'ondricka.lucie@example.net',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'BCD4BwFJRZ',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'xgleichner',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'role_id' => 2,
                'name' => '項傑',
                'email' => 'jswaniawski@example.net',
                'avatar' => 'users/default.png',
                'email_verified_at' => '2020-04-20 20:20:27',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'peLQ5uXRoj04AzaXwEdUdxlJssu63nflgZzMhlxOheHi37KIgH4ZDSClBaCY',
                'settings' => NULL,
                'created_at' => '2020-04-20 20:20:27',
                'updated_at' => '2020-04-20 20:20:27',
                'username' => 'satterfield.helene',
                'provider' => NULL,
                'provider_id' => NULL,
            ),
        ));
        
        
    }
}