<?php

use Illuminate\Database\Seeder;

class ExampleMenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => '控制面板',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2020-04-20 18:03:48',
                'updated_at' => '2020-04-20 18:03:48',
                'route' => 'voyager.dashboard',
                'parameters' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => '媒體',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2020-04-20 18:03:48',
                'updated_at' => '2020-04-20 19:53:03',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => '用戶',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2020-04-20 18:03:48',
                'updated_at' => '2020-04-20 18:03:48',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => '角色',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2020-04-20 18:03:48',
                'updated_at' => '2020-04-20 18:03:48',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => '工具',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2020-04-20 18:03:48',
                'updated_at' => '2020-04-21 00:04:02',
                'route' => NULL,
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => '側邊欄管理',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2020-04-20 18:03:48',
                'updated_at' => '2020-04-20 19:53:03',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => '資料庫',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2020-04-20 18:03:48',
                'updated_at' => '2020-04-20 19:53:03',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => '指南針',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2020-04-20 18:03:48',
                'updated_at' => '2020-04-20 19:53:03',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 5,
                'created_at' => '2020-04-20 18:03:48',
                'updated_at' => '2020-04-20 19:53:03',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => '設定',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2020-04-20 18:03:48',
                'updated_at' => '2020-04-21 00:04:02',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Hooks',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-hook',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2020-04-20 18:03:48',
                'updated_at' => '2020-04-21 00:04:02',
                'route' => 'voyager.hooks',
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => 2,
                'title' => '首頁',
                'url' => '\\',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2020-04-20 18:08:16',
                'updated_at' => '2020-04-20 18:11:58',
                'route' => NULL,
                'parameters' => '',
            ),
            12 => 
            array (
                'id' => 13,
                'menu_id' => 2,
                'title' => 'Blade示範',
                'url' => '/demo',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2020-04-20 18:10:16',
                'updated_at' => '2020-04-20 18:14:08',
                'route' => NULL,
                'parameters' => '',
            ),
            13 => 
            array (
                'id' => 14,
                'menu_id' => 2,
                'title' => '其他測試區',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2020-04-20 18:11:23',
                'updated_at' => '2020-04-20 18:15:52',
                'route' => NULL,
                'parameters' => '',
            ),
            14 => 
            array (
                'id' => 15,
                'menu_id' => 2,
                'title' => '新增資料',
                'url' => '/addItem',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 14,
                'order' => 1,
                'created_at' => '2020-04-20 18:11:53',
                'updated_at' => '2020-04-20 18:11:58',
                'route' => NULL,
                'parameters' => '',
            ),
            15 => 
            array (
                'id' => 16,
                'menu_id' => 2,
                'title' => '更新資料',
                'url' => 'updateItem/1',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 14,
                'order' => 2,
                'created_at' => '2020-04-20 18:12:18',
                'updated_at' => '2020-04-20 18:12:21',
                'route' => NULL,
                'parameters' => '',
            ),
            16 => 
            array (
                'id' => 17,
                'menu_id' => 2,
                'title' => '刪除資料',
                'url' => '/deleteItem/1',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 14,
                'order' => 3,
                'created_at' => '2020-04-20 18:12:45',
                'updated_at' => '2020-04-20 18:12:51',
                'route' => NULL,
                'parameters' => '',
            ),
            17 => 
            array (
                'id' => 18,
                'menu_id' => 2,
                'title' => '顯示FlashMessage',
                'url' => '/showflashmsg',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 14,
                'order' => 4,
                'created_at' => '2020-04-20 18:13:09',
                'updated_at' => '2020-04-20 18:13:25',
                'route' => NULL,
                'parameters' => '',
            ),
            18 => 
            array (
                'id' => 19,
                'menu_id' => 2,
                'title' => '商店頁',
                'url' => '/shop',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2020-04-20 18:14:03',
                'updated_at' => '2020-04-20 18:14:08',
                'route' => NULL,
                'parameters' => '',
            ),
            19 => 
            array (
                'id' => 20,
                'menu_id' => 2,
                'title' => '測試購物車',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2020-04-20 18:15:39',
                'updated_at' => '2020-04-20 18:15:52',
                'route' => NULL,
                'parameters' => '',
            ),
            20 => 
            array (
                'id' => 21,
                'menu_id' => 2,
                'title' => '新增購物車',
                'url' => '/addCart/1',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 20,
                'order' => 1,
                'created_at' => '2020-04-20 18:16:17',
                'updated_at' => '2020-04-21 13:08:55',
                'route' => NULL,
                'parameters' => '',
            ),
            21 => 
            array (
                'id' => 22,
                'menu_id' => 2,
                'title' => '更新購物車',
                'url' => '/updateCart/1',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 20,
                'order' => 2,
                'created_at' => '2020-04-20 18:16:53',
                'updated_at' => '2020-04-21 13:09:02',
                'route' => NULL,
                'parameters' => '',
            ),
            22 => 
            array (
                'id' => 23,
                'menu_id' => 2,
                'title' => '移除購物車',
                'url' => '/removeCart/1',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 20,
                'order' => 3,
                'created_at' => '2020-04-20 18:17:06',
                'updated_at' => '2020-04-21 13:09:08',
                'route' => NULL,
                'parameters' => '',
            ),
            23 => 
            array (
                'id' => 24,
                'menu_id' => 2,
                'title' => '顯示購物車',
                'url' => '/showCart',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 20,
                'order' => 4,
                'created_at' => '2020-04-20 18:17:22',
                'updated_at' => '2020-04-20 18:17:46',
                'route' => NULL,
                'parameters' => '',
            ),
            24 => 
            array (
                'id' => 25,
                'menu_id' => 2,
                'title' => '確認購物車',
                'url' => '/checkCart',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 20,
                'order' => 5,
                'created_at' => '2020-04-20 18:18:09',
                'updated_at' => '2020-04-20 18:18:14',
                'route' => NULL,
                'parameters' => '',
            ),
            25 => 
            array (
                'id' => 26,
                'menu_id' => 2,
                'title' => '顯示小/總計',
                'url' => '/showTotal',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 20,
                'order' => 6,
                'created_at' => '2020-04-20 18:18:42',
                'updated_at' => '2020-04-20 18:18:48',
                'route' => NULL,
                'parameters' => '',
            ),
            26 => 
            array (
                'id' => 27,
                'menu_id' => 2,
                'title' => '清除購物車',
                'url' => '/clearCart',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 20,
                'order' => 7,
                'created_at' => '2020-04-20 18:19:16',
                'updated_at' => '2020-04-20 18:19:21',
                'route' => NULL,
                'parameters' => '',
            ),
            27 => 
            array (
                'id' => 30,
                'menu_id' => 1,
                'title' => '分類集',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-folder',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2020-04-20 19:48:36',
                'updated_at' => '2020-04-20 19:53:01',
                'route' => 'voyager.cgies.index',
                'parameters' => NULL,
            ),
            28 => 
            array (
                'id' => 31,
                'menu_id' => 1,
                'title' => '商品集',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-paint-bucket',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2020-04-20 19:52:25',
                'updated_at' => '2020-04-20 19:53:07',
                'route' => 'voyager.items.index',
                'parameters' => NULL,
            ),
            29 => 
            array (
                'id' => 32,
                'menu_id' => 1,
                'title' => '網頁元素集',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-browser',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2020-04-21 00:03:26',
                'updated_at' => '2020-04-21 00:04:02',
                'route' => 'voyager.elements.index',
                'parameters' => NULL,
            ),
            30 => 
            array (
                'id' => 33,
                'menu_id' => 4,
                'title' => 'Laravel',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2020-04-21 00:53:47',
                'updated_at' => '2020-04-21 00:56:40',
                'route' => NULL,
                'parameters' => '',
            ),
            31 => 
            array (
                'id' => 34,
                'menu_id' => 4,
                'title' => '社群',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2020-04-21 00:55:05',
                'updated_at' => '2020-04-21 00:56:40',
                'route' => NULL,
                'parameters' => '',
            ),
            32 => 
            array (
                'id' => 35,
                'menu_id' => 4,
                'title' => '文件',
                'url' => 'https://laravel.com/docs/5.8',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 33,
                'order' => 2,
                'created_at' => '2020-04-21 00:56:25',
                'updated_at' => '2020-04-21 00:57:29',
                'route' => NULL,
                'parameters' => '',
            ),
            33 => 
            array (
                'id' => 36,
                'menu_id' => 4,
                'title' => '官網',
                'url' => 'https://laravel.com/',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 33,
                'order' => 1,
                'created_at' => '2020-04-21 00:57:25',
                'updated_at' => '2020-04-21 00:57:29',
                'route' => NULL,
                'parameters' => '',
            ),
            34 => 
            array (
                'id' => 37,
                'menu_id' => 4,
                'title' => 'Voyager套件',
                'url' => 'https://voyager.devdojo.com/',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 33,
                'order' => 3,
                'created_at' => '2020-04-21 00:58:22',
                'updated_at' => '2020-04-21 00:58:27',
                'route' => NULL,
                'parameters' => '',
            ),
            35 => 
            array (
                'id' => 38,
                'menu_id' => 4,
                'title' => '哥布林學苑',
                'url' => 'https://goblinlab.org',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 34,
                'order' => 1,
                'created_at' => '2020-04-21 00:58:54',
                'updated_at' => '2020-04-21 00:58:58',
                'route' => NULL,
                'parameters' => '',
            ),
            36 => 
            array (
                'id' => 39,
                'menu_id' => 4,
                'title' => '哥布林頻道',
                'url' => 'https://www.youtube.com/channel/UCRQc4X-HryBeaHiqyvc9Y7w',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 34,
                'order' => 2,
                'created_at' => '2020-04-21 01:00:13',
                'updated_at' => '2020-04-21 01:00:17',
                'route' => NULL,
                'parameters' => '',
            ),
            37 => 
            array (
                'id' => 40,
                'menu_id' => 4,
                'title' => '哥布林粉絲頁',
                'url' => 'https://www.facebook.com/goblinLab',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 34,
                'order' => 3,
                'created_at' => '2020-04-21 01:01:10',
                'updated_at' => '2020-04-21 01:01:17',
                'route' => NULL,
                'parameters' => '',
            ),
            38 => 
            array (
                'id' => 41,
                'menu_id' => 2,
                'title' => '本地化',
                'url' => '/localized',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 14,
                'order' => 5,
                'created_at' => '2020-04-21 17:24:45',
                'updated_at' => '2020-04-21 17:24:50',
                'route' => NULL,
                'parameters' => '',
            ),
        ));
        
        
    }
}